"""
Optional Stage 4 LLM Explanation Polisher with Blueprint Guardrails.

Owns the optional Stage 4 LLM polishing behavior.
Enforces project blueprint guardrails:
- Output MUST contain "consistent with" (case-insensitive)
- Output MUST NOT contain "confirms", "detects", "proves" (case-insensitive)
- Validation failure or LLM errors MUST fall back to the Stage 3 deterministic template.
"""

from typing import Any, Callable, Dict, Optional


def validate_llm_guardrails(text: str) -> bool:
    """
    Validates Stage 4 LLM polished output against project blueprint guardrails:
    - Must contain: "consistent with" (case-insensitive)
    - Must NOT contain: "confirms", "detects", "proves" (case-insensitive)

    :param text: Text generated by LLM.
    :return: True if text satisfies all blueprint guardrails, False otherwise.
    """
    if not text or not isinstance(text, str):
        return False

    text_lower = text.lower()

    # Required phrase check
    if "consistent with" not in text_lower:
        return False

    # Forbidden words check
    forbidden_words = ("confirms", "detects", "proves")
    for forbidden in forbidden_words:
        if forbidden in text_lower:
            return False

    return True


def polish_change_description(
    deterministic_description: str,
    config: Optional[Dict[str, Any]] = None,
    llm_callable: Optional[Callable[[str], str]] = None
) -> str:
    """
    Stage 4 LLM narrative polishing function.

    If polishing is enabled and an injectable llm_callable (or API client) is provided,
    invokes the LLM to refine the description. If the LLM is unavailable, disabled,
    raises an exception, or if the generated text fails guardrail validation, the function
    strictly falls back to returning the original deterministic_description.

    :param deterministic_description: Stage 3 rule-based text summary.
    :param config: Optional configuration options for LLM polish (e.g., {"enabled": True}).
    :param llm_callable: Optional injectable LLM generation function for testing/decoupling.
    :return: Refined narrative change description string if valid, else deterministic_description.
    """
    if not deterministic_description or not isinstance(deterministic_description, str):
        return deterministic_description or ""

    # Check configuration flags if provided
    if config and isinstance(config, dict) and not config.get("enabled", True):
        return deterministic_description

    # If no LLM callable or client is provided, fall back to deterministic template
    if llm_callable is None:
        return deterministic_description

    try:
        polished_output = llm_callable(deterministic_description)
    except Exception:
        # LLM exception fallback
        return deterministic_description

    if not polished_output or not isinstance(polished_output, str):
        return deterministic_description

    # Validate against blueprint guardrails
    if validate_llm_guardrails(polished_output):
        return polished_output

    # Guardrail validation failure fallback
    return deterministic_description
